keys:
  users:
    - &user "age1nhssvcts5qr9m3gjl2ps5p4ss7nez6nnhjncrvwm0gpy7x0nqeeq97tm9v"
  hosts:
    - &laptop "age1v9s8jfemdur60pn7gdqd9rcl9tj0rzgd2f0uwspteeyg557z6dgqs8ezu8"
    - &workstation "age16ly8zs8hvvlht9yzg7k6dsyegsd0vmwrfrnhwjnd87f4agh4u5hs9zactw"
creation_rules:
  - path_regex: ^install/[[:print:]]+$
    key_groups:
      - age:
          - *user
          - *laptop
          - *workstation
  - path_regex: ^hosts/laptop/[[:print:]]+$
    key_groups:
      - age:
          - *user
          - *laptop
  - path_regex: ^hosts/workstation/[[:print:]]+$
    key_groups:
      - age:
          - *user
          - *workstation
