homeassistant: ENC[AES256_GCM,data:bPpD6edw3za9s55HerkHC3YEblf0l7bqcbcZyl7g1sPtCKkNugO7kqi4XWk9SF2zr3OiziQx3zImnXyu658nr4EGeCzLY2pDIitZ0B/04fS3Lrzj8lyrMmpDAu4Pe4PAZB752BWzZWoSUEAYxJC7nvcTlEYnKYd5dQxWmrryxJ90LwF9SkzHmR9VszLjgguw+ctuPolBOvXV9+bk9voFvnTAtZQLIDpPU8jOtVIRO9XNgN3I44F3,iv:lP4TPcORdLNryEjN3RTnByZC9oO/ftLbQVuTrg8AcVk=,tag:cXmYXddvvWeiEkcI81iiSA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nhssvcts5qr9m3gjl2ps5p4ss7nez6nnhjncrvwm0gpy7x0nqeeq97tm9v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxSXI0RUpXa0MzNmFSVHhD
            K3JaYjFSNVAxUkY4QzZuQVVGWWhXNzh5ZFFRCjZNUVZONHgvT2RBdy9EZE9kbDRS
            TWVRb0ZMYzFwWlZVS3MrRllQbnZKeVUKLS0tIFJ1YXplN1VMM1JrSDV0UzlWbWhu
            SngvdE1BZ3ZBT0MwR2ZiMjUrV2NxTVEKgukwMCQLvdzT6UqOzdY9gqNI3RqsG/fO
            FtiFAXX4ZKzH2GGISbA2BSi+oAjyX5xaf77ZgaKRCuAs1DmpEBPa2A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-21T23:57:43Z"
    mac: ENC[AES256_GCM,data:JtIfRwFyoUbO6seqq5qOnq3+zXNJtiVbDR0j5u3xrFuXtwsW8CztsTFrptdd/+6ta0cHW50b8Se/TEUQQESuk0GEc0En3Tw0ihaVfFF7aIBSno+04P4RDUSQ6YJUKjDJ5SDTGHcchE9R8Hn5ODoY7smtBXykZU7NW02cdQs5PLE=,iv:YMRXDxqGLGp8wypN7XVc0w7hLc8dL7EV5JKpDopzyvE=,tag:OHcO4Yy2mAA38CNRNPLl+A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.2
