homeassistant: ENC[AES256_GCM,data:bPpD6edw3za9s55HerkHC3YEblf0l7bqcbcZyl7g1sPtCKkNugO7kqi4XWk9SF2zr3OiziQx3zImnXyu658nr4EGeCzLY2pDIitZ0B/04fS3Lrzj8lyrMmpDAu4Pe4PAZB752BWzZWoSUEAYxJC7nvcTlEYnKYd5dQxWmrryxJ90LwF9SkzHmR9VszLjgguw+ctuPolBOvXV9+bk9voFvnTAtZQLIDpPU8jOtVIRO9XNgN3I44F3,iv:lP4TPcORdLNryEjN3RTnByZC9oO/ftLbQVuTrg8AcVk=,tag:cXmYXddvvWeiEkcI81iiSA==,type:str]
rdp:
    password: ENC[AES256_GCM,data:QEJcKf7gy2sRpOrz5Q==,iv:4VW2o/6eMhJxAEvYuPxN2S6zGzqf46troAFaV2YAHKA=,tag:apLCh+MWhs3Zmb7GC0/bVw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nhssvcts5qr9m3gjl2ps5p4ss7nez6nnhjncrvwm0gpy7x0nqeeq97tm9v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxSXI0RUpXa0MzNmFSVHhD
            K3JaYjFSNVAxUkY4QzZuQVVGWWhXNzh5ZFFRCjZNUVZONHgvT2RBdy9EZE9kbDRS
            TWVRb0ZMYzFwWlZVS3MrRllQbnZKeVUKLS0tIFJ1YXplN1VMM1JrSDV0UzlWbWhu
            SngvdE1BZ3ZBT0MwR2ZiMjUrV2NxTVEKgukwMCQLvdzT6UqOzdY9gqNI3RqsG/fO
            FtiFAXX4ZKzH2GGISbA2BSi+oAjyX5xaf77ZgaKRCuAs1DmpEBPa2A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-08T15:04:34Z"
    mac: ENC[AES256_GCM,data:DAD/Jo4efzm531vmS4vxUEQyZG3Con/9gU886beDmLUVp3IZJIJLo+VejA39O+pngO07X3Mu142JUvW4qm6J629ITCu/lBwaBXC3QwwOmPgbO1vteCkUgIvE/nLEPSXkg2BFpj/kjOENAjBAVda8/E95g0R0CPxNjokp/QOtzEE=,iv:jIPSJxEhRpEgLqGEwPLYzY1ZjpRy5fbmG0eIWJrhc6U=,tag:SZDczqUiW8EE3TrQIogFxg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
