homeassistant: ENC[AES256_GCM,data:AeyaWq9s9Ifr1okQ8V3YzogyXEW602DOi35UZahv06QsUra6lSy4mMORsS5sAZ8lY7qdLQEf9JnzBSaF9hjBxEhobHhuW7JFS46GI0oSBGrSpl6qBneUEsDf8HWngf61aZ1+0HgFqLzmRSDdZd0k0s+p9JV8+qFoc7C1irDOyQ7KVZez0I+36eAkP7uXBxJgF8HODRYngwmkAi00x2L8Ql4rOCpIDq0TZ06lQByN4Il75h/yl4gv,iv:Cm4FVxVFutqqAoq5c6BiUJb8ADhDLJ0ukS3U7J8sZfk=,tag:1rxp4tM19lrw5EeB7dd6dw==,type:str]
rdp:
    password: ENC[AES256_GCM,data:QEJcKf7gy2sRpOrz5Q==,iv:4VW2o/6eMhJxAEvYuPxN2S6zGzqf46troAFaV2YAHKA=,tag:apLCh+MWhs3Zmb7GC0/bVw==,type:str]
user:
    password: ENC[AES256_GCM,data:LtfVrXe4s6feXYE4UEVgEvm3upAJNDo0exZV0znBFTnBnfnxsx8jZ1HHmQ+pKnzeS/Cq1q8zq3B4/XWPAvJ2rADyaSKzQPMzqA==,iv:tEGgKR3Ee9ahDfoSV541KNjUQmOtXS9qpuguhxwMVww=,tag:ES8RdA72AeCGAHIdPB0AZA==,type:str]
wifi.env: ENC[AES256_GCM,data:cYLH/MwAz+eeSdjjY+7LnfOjxu9dJ8VOmyecp3lAA/fMgntiBvYHh7/5g+zExxOTj3pQsRu5dHH2jkahTlIckGBqj6BF8vYVQ8LbVthRNXhjkm4FBhazVJWPcimfFqn+jcayRKUQWQEXn8y2KH0XE51MmEdA39Nc5Gbn1Ftem5VqhV0MettvUZ3ZWQMe6LH7oyjrzrsiVi92TsYX7JhtcITN/TqwWwGLaEhdY8O5XuPzm2QwHMeP3OPchgHce6ZheUXlZFIepwBwM1J0i7QCPcqjHEX0d4GzGZlvnxUHWUm/ueu/lukcYbzKWvcETblZvDB2v4bB7T2yu+PnLTTBVBe8vXH6UrtwhuwkCYrDpSnS01L4V8+OuH+mjumFEmoazpy+Cy9VnvF9KVA6G2Qe2ZKal7RDvV7N0VDrnieXxxTX,iv:Ewt8eikQ8588OhSYsmOzUOngQqniQzSiiGG+mugaFsw=,tag:Vj0Sqkn1ul9CbH+/xslFfg==,type:str]
sops:
    age:
        - recipient: age1nhssvcts5qr9m3gjl2ps5p4ss7nez6nnhjncrvwm0gpy7x0nqeeq97tm9v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxSXI0RUpXa0MzNmFSVHhD
            K3JaYjFSNVAxUkY4QzZuQVVGWWhXNzh5ZFFRCjZNUVZONHgvT2RBdy9EZE9kbDRS
            TWVRb0ZMYzFwWlZVS3MrRllQbnZKeVUKLS0tIFJ1YXplN1VMM1JrSDV0UzlWbWhu
            SngvdE1BZ3ZBT0MwR2ZiMjUrV2NxTVEKgukwMCQLvdzT6UqOzdY9gqNI3RqsG/fO
            FtiFAXX4ZKzH2GGISbA2BSi+oAjyX5xaf77ZgaKRCuAs1DmpEBPa2A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-11T20:19:03Z"
    mac: ENC[AES256_GCM,data:swI8s5sM7sFNUy06cJx7ghRzdUhub9UfXo/KKhvSKxt3u8wb5R/5tEhrUO26FSpNTFXZ/Cfl3PMHnEeyZCOKcT4BCG7Z+V9Keu8LNVqF7qnw4Exh7pztOhYD35xPP0WezkY+e3rzq/Qyk5sfYmw1fgj8vA0ys8w1X6128QOBQmo=,iv:aoR3jbKz/n9nt1lub6IUDkGAJprNaiYOmA1NojR6Gq0=,tag:xfT0NI/g7CXCsbAOrmF0iA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
