homeassistant: ENC[AES256_GCM,data:bPpD6edw3za9s55HerkHC3YEblf0l7bqcbcZyl7g1sPtCKkNugO7kqi4XWk9SF2zr3OiziQx3zImnXyu658nr4EGeCzLY2pDIitZ0B/04fS3Lrzj8lyrMmpDAu4Pe4PAZB752BWzZWoSUEAYxJC7nvcTlEYnKYd5dQxWmrryxJ90LwF9SkzHmR9VszLjgguw+ctuPolBOvXV9+bk9voFvnTAtZQLIDpPU8jOtVIRO9XNgN3I44F3,iv:lP4TPcORdLNryEjN3RTnByZC9oO/ftLbQVuTrg8AcVk=,tag:cXmYXddvvWeiEkcI81iiSA==,type:str]
rdp:
    password: ENC[AES256_GCM,data:QEJcKf7gy2sRpOrz5Q==,iv:4VW2o/6eMhJxAEvYuPxN2S6zGzqf46troAFaV2YAHKA=,tag:apLCh+MWhs3Zmb7GC0/bVw==,type:str]
user:
    password: ENC[AES256_GCM,data:LtfVrXe4s6feXYE4UEVgEvm3upAJNDo0exZV0znBFTnBnfnxsx8jZ1HHmQ+pKnzeS/Cq1q8zq3B4/XWPAvJ2rADyaSKzQPMzqA==,iv:tEGgKR3Ee9ahDfoSV541KNjUQmOtXS9qpuguhxwMVww=,tag:ES8RdA72AeCGAHIdPB0AZA==,type:str]
wifi.env: ENC[AES256_GCM,data:tfFwovxOflnMpSwlfvh3jQxbdC90WtV8b298tLPT61u6vR+Nd9XbfhqEeeFQPOon/MwbilhFbYCag8V/LrKVI4qansBLuhfPvG5E+91FKxsn77BeX//p4yxJmgYKw0eZFij0BpScRNnf8vt8VZoWDH6fdnqDp+Op3o3FN6O/thQ31d9THxpheYhUb2nMOWfDG8EJ0AaB0nONCAHHTtqT+D4Lx1FDRXa0u9e3xWqx1nQv34+8478udyLD2wMKUfmQKAs0KqJfWr2/YkP3MsPHhcbmyfyEpG5ImnLSnx0/dh4a+ipOInlw3Y+41n8N7W3+9gY2kTjzQglfBF1RFsdWJ7tGuHozSeIzHfL3AIC4gtKBz4t3JDoN3/z4z53rfbVpoergZ3cXHg2MAV8EaweEpX06rSM=,iv:ZmltdetPcTBUDhypTRoG0/72MEVh/dSD8EQCp0+minc=,tag:1d2bDXCwJ04SW0pf2kvZeg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nhssvcts5qr9m3gjl2ps5p4ss7nez6nnhjncrvwm0gpy7x0nqeeq97tm9v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxSXI0RUpXa0MzNmFSVHhD
            K3JaYjFSNVAxUkY4QzZuQVVGWWhXNzh5ZFFRCjZNUVZONHgvT2RBdy9EZE9kbDRS
            TWVRb0ZMYzFwWlZVS3MrRllQbnZKeVUKLS0tIFJ1YXplN1VMM1JrSDV0UzlWbWhu
            SngvdE1BZ3ZBT0MwR2ZiMjUrV2NxTVEKgukwMCQLvdzT6UqOzdY9gqNI3RqsG/fO
            FtiFAXX4ZKzH2GGISbA2BSi+oAjyX5xaf77ZgaKRCuAs1DmpEBPa2A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-05T11:47:33Z"
    mac: ENC[AES256_GCM,data:eivbCd6poBfkk95/tjS3iWTHSE08iqVFhVOMJ3cWtQHwzgxWmtdoNFsWGZi28bBNdqNsRMn/xRLKgcpwxz6icX4G+Tsz/GYk38Y93nEVDG57mjiBJg3OBZXJn1pL1eLLGH4nJCxP4xU6uFtTSz6sLHxs+nowc4QbmKOApnnzUCc=,iv:vtY0/Hv8HcwrOIFu9EbYR147ZK9iUftvHtdHCqF3d8Y=,tag:zxtGzWFXXuzCvaB+oQRfbA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
