homeassistant: ENC[AES256_GCM,data:AeyaWq9s9Ifr1okQ8V3YzogyXEW602DOi35UZahv06QsUra6lSy4mMORsS5sAZ8lY7qdLQEf9JnzBSaF9hjBxEhobHhuW7JFS46GI0oSBGrSpl6qBneUEsDf8HWngf61aZ1+0HgFqLzmRSDdZd0k0s+p9JV8+qFoc7C1irDOyQ7KVZez0I+36eAkP7uXBxJgF8HODRYngwmkAi00x2L8Ql4rOCpIDq0TZ06lQByN4Il75h/yl4gv,iv:Cm4FVxVFutqqAoq5c6BiUJb8ADhDLJ0ukS3U7J8sZfk=,tag:1rxp4tM19lrw5EeB7dd6dw==,type:str]
rdp:
    password: ENC[AES256_GCM,data:QEJcKf7gy2sRpOrz5Q==,iv:4VW2o/6eMhJxAEvYuPxN2S6zGzqf46troAFaV2YAHKA=,tag:apLCh+MWhs3Zmb7GC0/bVw==,type:str]
user:
    password: ENC[AES256_GCM,data:LtfVrXe4s6feXYE4UEVgEvm3upAJNDo0exZV0znBFTnBnfnxsx8jZ1HHmQ+pKnzeS/Cq1q8zq3B4/XWPAvJ2rADyaSKzQPMzqA==,iv:tEGgKR3Ee9ahDfoSV541KNjUQmOtXS9qpuguhxwMVww=,tag:ES8RdA72AeCGAHIdPB0AZA==,type:str]
wifi.env: ENC[AES256_GCM,data:tfFwovxOflnMpSwlfvh3jQxbdC90WtV8b298tLPT61u6vR+Nd9XbfhqEeeFQPOon/MwbilhFbYCag8V/LrKVI4qansBLuhfPvG5E+91FKxsn77BeX//p4yxJmgYKw0eZFij0BpScRNnf8vt8VZoWDH6fdnqDp+Op3o3FN6O/thQ31d9THxpheYhUb2nMOWfDG8EJ0AaB0nONCAHHTtqT+D4Lx1FDRXa0u9e3xWqx1nQv34+8478udyLD2wMKUfmQKAs0KqJfWr2/YkP3MsPHhcbmyfyEpG5ImnLSnx0/dh4a+ipOInlw3Y+41n8N7W3+9gY2kTjzQglfBF1RFsdWJ7tGuHozSeIzHfL3AIC4gtKBz4t3JDoN3/z4z53rfbVpoergZ3cXHg2MAV8EaweEpX06rSM=,iv:ZmltdetPcTBUDhypTRoG0/72MEVh/dSD8EQCp0+minc=,tag:1d2bDXCwJ04SW0pf2kvZeg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nhssvcts5qr9m3gjl2ps5p4ss7nez6nnhjncrvwm0gpy7x0nqeeq97tm9v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxSXI0RUpXa0MzNmFSVHhD
            K3JaYjFSNVAxUkY4QzZuQVVGWWhXNzh5ZFFRCjZNUVZONHgvT2RBdy9EZE9kbDRS
            TWVRb0ZMYzFwWlZVS3MrRllQbnZKeVUKLS0tIFJ1YXplN1VMM1JrSDV0UzlWbWhu
            SngvdE1BZ3ZBT0MwR2ZiMjUrV2NxTVEKgukwMCQLvdzT6UqOzdY9gqNI3RqsG/fO
            FtiFAXX4ZKzH2GGISbA2BSi+oAjyX5xaf77ZgaKRCuAs1DmpEBPa2A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-11T18:13:34Z"
    mac: ENC[AES256_GCM,data:M2gYdOuGiopmnEtFFi4yXCld8OUtdBT2Du5CXrS7/U5YspVT04bkhuSWRhD5cGomzgzWgWwGcn1vOtnfmATRZZh0xESXA7AHAKi56yWrLE0DPoEKMg3R6ZNPiSPLgIL4Z+acP8r/dls/eLuuT4A+A0df6STzLAUDb3b8Rb4MtR8=,iv:WHD1asKObgPnMVUwfkWJaNMTb0Z23F6yGz4h1UdD9Sg=,tag:90HVTPEdRUx6q1NtoVhdZg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
