homeassistant: ENC[AES256_GCM,data:bPpD6edw3za9s55HerkHC3YEblf0l7bqcbcZyl7g1sPtCKkNugO7kqi4XWk9SF2zr3OiziQx3zImnXyu658nr4EGeCzLY2pDIitZ0B/04fS3Lrzj8lyrMmpDAu4Pe4PAZB752BWzZWoSUEAYxJC7nvcTlEYnKYd5dQxWmrryxJ90LwF9SkzHmR9VszLjgguw+ctuPolBOvXV9+bk9voFvnTAtZQLIDpPU8jOtVIRO9XNgN3I44F3,iv:lP4TPcORdLNryEjN3RTnByZC9oO/ftLbQVuTrg8AcVk=,tag:cXmYXddvvWeiEkcI81iiSA==,type:str]
rdp:
    password: ENC[AES256_GCM,data:QEJcKf7gy2sRpOrz5Q==,iv:4VW2o/6eMhJxAEvYuPxN2S6zGzqf46troAFaV2YAHKA=,tag:apLCh+MWhs3Zmb7GC0/bVw==,type:str]
user:
    password: ENC[AES256_GCM,data:LtfVrXe4s6feXYE4UEVgEvm3upAJNDo0exZV0znBFTnBnfnxsx8jZ1HHmQ+pKnzeS/Cq1q8zq3B4/XWPAvJ2rADyaSKzQPMzqA==,iv:tEGgKR3Ee9ahDfoSV541KNjUQmOtXS9qpuguhxwMVww=,tag:ES8RdA72AeCGAHIdPB0AZA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nhssvcts5qr9m3gjl2ps5p4ss7nez6nnhjncrvwm0gpy7x0nqeeq97tm9v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxSXI0RUpXa0MzNmFSVHhD
            K3JaYjFSNVAxUkY4QzZuQVVGWWhXNzh5ZFFRCjZNUVZONHgvT2RBdy9EZE9kbDRS
            TWVRb0ZMYzFwWlZVS3MrRllQbnZKeVUKLS0tIFJ1YXplN1VMM1JrSDV0UzlWbWhu
            SngvdE1BZ3ZBT0MwR2ZiMjUrV2NxTVEKgukwMCQLvdzT6UqOzdY9gqNI3RqsG/fO
            FtiFAXX4ZKzH2GGISbA2BSi+oAjyX5xaf77ZgaKRCuAs1DmpEBPa2A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-30T10:32:41Z"
    mac: ENC[AES256_GCM,data:EdJ23udXbEB/FJk7eOJYHo9mvlTaMtUtbrIa/TetUwVzyCXmYSC+GW9kofAU/0ffeGP36Q6sT9/SWRJki4YzgpgOSU18LKwo6K2x8+Z+2FsGgnBzlgcXQMsLjGqWKQuiO81HcJWfXmh3lzYwll2Ol7K4nIp9itcEGsnkqEiW7rw=,iv:plmz+CYl7Dl+qocwHNilZiu5Eb7IU3cBv4kNU1J9Fy4=,tag:haKkVi4TdkpjA93wvmoqag==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
